name: Fetch Ox Image

on:
  schedule:
    - cron: '*/15 * * * *'  # 15分ごと（UTC）
  workflow_dispatch:

jobs:
  update-ox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decide which image to fetch
        id: decide
        run: |
          # 15分ごとに交互に切り替え
          minute=$(date -u +'%M')
          if [ $(( (10#$minute / 15) % 2 )) -eq 0 ]; then
            echo "url=http://andersan.riis.okayama-u.ac.jp:8082/images/Ox.png" >> $GITHUB_OUTPUT
          else
            echo "url=http://andersan.riis.okayama-u.ac.jp:8082/images/Temp.png" >> $GITHUB_OUTPUT
          fi

      - name: Fetch and overwrite Ox.png
        run: |
          mkdir -p images docs
          curl -s -o images/Ox.png "${{ steps.decide.outputs.url }}"
          cp -f images/Ox.png docs/Ox.png

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -f images/Ox.png docs/Ox.png
          git commit -m "Force update Ox.png" || echo "No changes to commit"
          git push
