name: Fetch Ox Image

on:
  schedule:
    - cron: '*/15 * * * *'  # 15分ごと（UTC）
  workflow_dispatch:

jobs:
  update-ox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch and overwrite Ox.png
        run: |
          mkdir -p images docs

          # オキシダント画像を取得
          curl -s -o images/Ox.png http://andersan.riis.okayama-u.ac.jp:8082/images/Ox.png

          # docsフォルダに強制コピー
          cp -f images/Ox.png docs/Ox.png

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # 強制的に追加（内容が同じでも）
          git add -f images/Ox.png docs/Ox.png

          git commit -m "Force update Ox.png" || echo "No changes to commit"
          git push
