name: Fetch Ox Image

on:
  schedule:
    - cron: '31 * * * *'  # 毎時31分（UTC）
  workflow_dispatch:

jobs:
  update-ox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch image
        run: |
          mkdir -p images
          curl -s -o images/Ox.png http://andersan.riis.okayama-u.ac.jp:8082/images/Ox.png

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add images/Ox.png
          git commit -m "Auto update Ox.png" || echo "No changes to commit"
          git push
