name: Alternate Ox and TEMP Images

on:
  schedule:
    - cron: '*/15 * * * *'  # 毎15分（UTC）に実行
  workflow_dispatch:

jobs:
  update-ox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch images from server
        run: |
          mkdir -p images docs
          curl -s -o images/Ox.png http://andersan.riis.okayama-u.ac.jp:8082/images/Ox.png
          curl -s -o images/TEMP.png http://andersan.riis.okayama-u.ac.jp:8082/images/TEMP.png

          # UTC現在時刻の分を取得（ゼロ埋め解除して整数にする）
          MINUTE=$(date -u +"%M")
          echo "Current UTC minute: $MINUTE"

          # 偶数分は Ox.png、奇数分は TEMP.png を docs/Ox.png にコピー
          if [ $((10#$MINUTE % 2)) -eq 0 ]; then
            cp images/Ox.png docs/Ox.png
            echo "▶ Copied Ox.png to docs/Ox.png"
          else
            cp images/TEMP.png docs/Ox.png
            echo "▶ Copied TEMP.png to docs/Ox.png"
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add images/Ox.png images/TEMP.png docs/Ox.png
          git commit -m "Auto update alternating Ox/TEMP every 15min" || echo "No changes to commit"
          git push
